# 모바일 게임 서비스 SLI/SLO 정의
# 게임 사용자 경험을 대표하는 핵심 지표와 목표

apiVersion: sre.observaility.com/v1
kind: ServiceLevelObjective
metadata:
  name: mobile-game-service
  namespace: production
  labels:
    service: mobile-game
    team: game-sre
    environment: production
spec:
  description: "모바일 게임 서비스 핵심 신뢰성 목표"

  # 1. 게임 서버 가용성 (핵심 SLI)
  slis:
    - name: game_server_availability
      description: "게임 서버 응답 성공률"
      sli:
        numerator: |
          sum(rate(game_requests_total{
            service="game-server",
            status_code!~"5..|4.."
          }[5m]))
        denominator: |
          sum(rate(game_requests_total{
            service="game-server"
          }[5m]))
        unit: "percentage"
      slo:
        target: 99.9
        window: 30d
        description: "월간 99.9% 가용성 목표"
      alerting:
        burn_rates:
          - window: 1h
            factor: 14.4  # 빠른 소진 (1시간)
            severity: critical
          - window: 6h
            factor: 6     # 느린 소진 (6시간)
            severity: warning

    # 2. 게임 액션 응답 지연시간
    - name: game_action_latency
      description: "게임 액션 응답 속도 (p95)"
      sli:
        numerator: |
          histogram_quantile(0.95,
            sum(rate(game_action_duration_seconds_bucket{
              service="game-server"
            }[5m])) by (le)
          )
        denominator: "1"
        unit: "seconds"
      slo:
        target: 0.5
        window: 30d
        description: "p95 지연시간 500ms 이하"
      alerting:
        thresholds:
          - threshold: 0.8
            severity: warning
          - threshold: 1.0
            severity: critical

    # 3. 게임 플레이 오류율
    - name: game_play_error_rate
      description: "게임 플레이 중 오류 발생률"
      sli:
        numerator: |
          sum(rate(game_errors_total{
            service="game-server",
            error_type="gameplay"
          }[5m]))
        denominator: |
          sum(rate(game_requests_total{
            service="game-server"
          }[5m]))
        unit: "percentage"
      slo:
        target: 0.1
        window: 30d
        description: "게임 플레이 오류율 0.1% 이하"
      alerting:
        burn_rates:
          - window: 1h
            factor: 14.4
            severity: critical

    # 4. 동시 접속자 수
    - name: concurrent_players
      description: "동시 게임 세션 수"
      sli:
        numerator: |
          max_over_time(game_sessions_active{
            service="game-server"
          }[5m])
        denominator: "1"
        unit: "count"
      slo:
        target: 10000
        window: 30d
        description: "최소 10,000명 동시 접속 지원"
      alerting:
        thresholds:
          - threshold: 8000
            severity: warning
          - threshold: 5000
            severity: critical

    # 5. 게임 매칭 성공률
    - name: game_matching_success_rate
      description: "게임 매칭 시스템 성공률"
      sli:
        numerator: |
          sum(rate(game_matching_requests_total{
            service="matchmaking",
            status="success"
          }[5m]))
        denominator: |
          sum(rate(game_matching_requests_total{
            service="matchmaking"
          }[5m]))
        unit: "percentage"
      slo:
        target: 95.0
        window: 30d
        description: "매칭 성공률 95% 이상"
      alerting:
        burn_rates:
          - window: 1h
            factor: 14.4
            severity: critical

    # 6. 게임 데이터 저장 성공률
    - name: game_data_persistence_success_rate
      description: "게임 진행 데이터 저장 성공률"
      sli:
        numerator: |
          sum(rate(game_data_save_total{
            service="game-persistence",
            status="success"
          }[5m]))
        denominator: |
          sum(rate(game_data_save_total{
            service="game-persistence"
          }[5m]))
        unit: "percentage"
      slo:
        target: 99.99
        window: 30d
        description: "데이터 저장 성공률 99.99% 이상"
      alerting:
        burn_rates:
          - window: 1h
            factor: 14.4
            severity: critical

  # 에러 버짓 정책
  error_budget:
    target: 0.1  # 0.1% 에러 버짓 (99.9% 가용성 기준)
    window: 30d
    policies:
      - name: deployment_freeze
        description: "에러 버짓 소진 시 배포 일시중지"
        threshold: 0.05  # 50% 소진 시
        action: "freeze_deployments"
      - name: rollback_trigger
        description: "에러 버짓 80% 소진 시 자동 롤백"
        threshold: 0.08  # 80% 소진 시
        action: "auto_rollback"

  # 게임 특화 운영 정책
  game_specific:
    peak_hours:
      - start: "18:00"
        end: "22:00"
        timezone: "Asia/Seoul"
        description: "저녁 피크 시간대"
        slo_multiplier: 1.2  # 피크 시간대 SLO 강화

    seasonal_events:
      - name: "holiday_events"
        description: "공휴일/이벤트 기간"
        slo_multiplier: 1.1
        auto_scale: true

    maintenance_windows:
      - day: "tuesday"
        start: "02:00"
        end: "06:00"
        timezone: "Asia/Seoul"
        description: "화요일 새벽 정기 점검"
        slo_exemption: true

  # 알림 및 에스컬레이션
  notifications:
    channels:
      - name: "game-sre-oncall"
        type: "slack"
        url: "https://hooks.slack.com/services/..."
        severity: ["critical", "warning"]

      - name: "game-ops-team"
        type: "pagerduty"
        escalation_policy: "game-sre-escalation"
        severity: ["critical"]

    templates:
      critical: |
        🚨 [CRITICAL] {{.Service}} SLO 위반
        SLI: {{.SLIName}}
        현재값: {{.CurrentValue}}
        목표값: {{.TargetValue}}
        에러 버짓 소진률: {{.BudgetBurnRate}}%

        즉시 대응이 필요합니다!

      warning: |
        ⚠️ [WARNING] {{.Service}} SLO 경고
        SLI: {{.SLIName}}
        현재값: {{.CurrentValue}}
        목표값: {{.TargetValue}}
        에러 버짓 소진률: {{.BudgetBurnRate}}%

  # 리뷰 및 개선 사이클
  review_cycle:
    frequency: "monthly"
    stakeholders:
      - "game-sre-team"
      - "game-development-team"
      - "product-management"
      - "customer-support"

    metrics:
      - "slo_achievement_rate"
      - "error_budget_consumption"
      - "incident_frequency"
      - "user_satisfaction_score"
      - "revenue_impact"
